// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mzuCRszeeZdCMSdpkmycrs
// Component: ZhULiaU9WIpl
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import * as pp from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_gv.module.css"; // plasmic-import: mzuCRszeeZdCMSdpkmycrs/projectcss
import sty from "./PlasmicButton.module.css"; // plasmic-import: ZhULiaU9WIpl/css
import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: VwtN0GCUtONh/icon

createPlasmicElementProxy;

export const PlasmicButton__VariantProps = new Array(
  "showStartIcon",
  "showEndIcon",
  "iconOnly",
  "colors",
  "size",
  "rounded",
  "states",
  "isDisabled"
);

export const PlasmicButton__ArgProps = new Array(
  "startIcon",
  "children",
  "endIcon",
  "link",
  "submitsForm",
  "target"
);

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicButton__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "showStartIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.showStartIcon
      },
      {
        path: "showEndIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.showEndIcon
      },
      {
        path: "iconOnly",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.iconOnly
      },
      {
        path: "colors",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.colors
      },
      {
        path: "size",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.size
      },
      {
        path: "rounded",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.rounded
      },
      {
        path: "states",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.states
      },
      {
        path: "isDisabled",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.isDisabled
      }
    ],

    [$props, $ctx, $refs]
  );

  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <p.Stack
      as={"button"}
      data-plasmic-name={"mobiledeposit"}
      data-plasmic-override={overrides.mobiledeposit}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.mobiledeposit,
        {
          [sty.mobiledepositcolors_black]: hasVariant(
            $state,
            "colors",
            "black"
          ),

          [sty.mobiledepositcolors_black_showEndIcon]:
            hasVariant($state, "showEndIcon", "showEndIcon") &&
            hasVariant($state, "colors", "black"),
          [sty.mobiledepositcolors_blue]: hasVariant($state, "colors", "blue"),
          [sty.mobiledepositcolors_gray]: hasVariant($state, "colors", "gray"),
          [sty.mobiledepositcolors_lightGrayOutline]: hasVariant(
            $state,
            "colors",
            "lightGrayOutline"
          ),

          [sty.mobiledepositcolors_lightGray]: hasVariant(
            $state,
            "colors",
            "lightGray"
          ),

          [sty.mobiledepositcolors_link]: hasVariant($state, "colors", "link"),
          [sty.mobiledepositcolors_white]: hasVariant(
            $state,
            "colors",
            "white"
          ),

          [sty.mobiledepositisDisabled]: hasVariant(
            $state,
            "isDisabled",
            "isDisabled"
          ),

          [sty.mobiledepositrounded]: hasVariant($state, "rounded", "rounded"),
          [sty.mobiledepositshowEndIcon]: hasVariant(
            $state,
            "showEndIcon",
            "showEndIcon"
          ),

          [sty.mobiledepositshowStartIcon]: hasVariant(
            $state,
            "showStartIcon",
            "showStartIcon"
          ),

          [sty.mobiledepositsize_large]: hasVariant($state, "size", "large"),
          [sty.mobiledepositsize_large_colors_black_showEndIcon]:
            hasVariant($state, "showEndIcon", "showEndIcon") &&
            hasVariant($state, "colors", "black") &&
            hasVariant($state, "size", "large"),
          [sty.mobiledepositsize_large_rounded]:
            hasVariant($state, "rounded", "rounded") &&
            hasVariant($state, "size", "large"),
          [sty.mobiledepositsize_large_rounded_colors_black_showEndIcon]:
            hasVariant($state, "showEndIcon", "showEndIcon") &&
            hasVariant($state, "colors", "black") &&
            hasVariant($state, "size", "large") &&
            hasVariant($state, "rounded", "rounded"),
          [sty.mobiledepositsize_narrow]: hasVariant($state, "size", "narrow"),
          [sty.mobiledepositsize_small]: hasVariant($state, "size", "small"),
          [sty.mobiledepositstates_active]: hasVariant(
            $state,
            "states",
            "active"
          )
        }
      )}
      ref={ref => {
        $refs["mobiledeposit"] = ref;
      }}
    >
      {(
        hasVariant($state, "iconOnly", "iconOnly")
          ? true
          : hasVariant($state, "showEndIcon", "showEndIcon")
          ? false
          : hasVariant($state, "showStartIcon", "showStartIcon")
          ? true
          : false
      ) ? (
        <div
          className={classNames(projectcss.all, sty.freeBox__emCka, {
            [sty.freeBoxiconOnly__emCkaBgbOt]: hasVariant(
              $state,
              "iconOnly",
              "iconOnly"
            ),

            [sty.freeBoxshowEndIcon__emCkahUlNp]: hasVariant(
              $state,
              "showEndIcon",
              "showEndIcon"
            ),

            [sty.freeBoxshowStartIcon__emCkaKm79C]: hasVariant(
              $state,
              "showStartIcon",
              "showStartIcon"
            ),

            [sty.freeBoxsize_large__emCkaBg0Pk]: hasVariant(
              $state,
              "size",
              "large"
            ),

            [sty.freeBoxsize_small__emCkaL58]: hasVariant(
              $state,
              "size",
              "small"
            )
          })}
        >
          {(hasVariant($state, "showEndIcon", "showEndIcon") ? true : true)
            ? p.renderPlasmicSlot({
                defaultContents: (
                  <MenuIcon
                    className={classNames(projectcss.all, sty.svg__oOszG)}
                    role={"img"}
                  />
                ),

                value: args.startIcon,
                className: classNames(sty.slotTargetStartIcon, {
                  [sty.slotTargetStartIconcolors_black]: hasVariant(
                    $state,
                    "colors",
                    "black"
                  ),

                  [sty.slotTargetStartIconcolors_blue]: hasVariant(
                    $state,
                    "colors",
                    "blue"
                  ),

                  [sty.slotTargetStartIconcolors_gray]: hasVariant(
                    $state,
                    "colors",
                    "gray"
                  ),

                  [sty.slotTargetStartIconshowEndIcon]: hasVariant(
                    $state,
                    "showEndIcon",
                    "showEndIcon"
                  ),

                  [sty.slotTargetStartIconsize_large]: hasVariant(
                    $state,
                    "size",
                    "large"
                  ),

                  [sty.slotTargetStartIconsize_small]: hasVariant(
                    $state,
                    "size",
                    "small"
                  )
                })
              })
            : null}
        </div>
      ) : null}
      {(hasVariant($state, "iconOnly", "iconOnly") ? true : true)
        ? p.renderPlasmicSlot({
            defaultContents: "Enter some text",
            value: args.children,
            className: classNames(sty.slotTargetChildren, {
              [sty.slotTargetChildrencolors_black]: hasVariant(
                $state,
                "colors",
                "black"
              ),

              [sty.slotTargetChildrencolors_blue]: hasVariant(
                $state,
                "colors",
                "blue"
              ),

              [sty.slotTargetChildrencolors_gray]: hasVariant(
                $state,
                "colors",
                "gray"
              ),

              [sty.slotTargetChildrencolors_link]: hasVariant(
                $state,
                "colors",
                "link"
              ),

              [sty.slotTargetChildreniconOnly]: hasVariant(
                $state,
                "iconOnly",
                "iconOnly"
              ),

              [sty.slotTargetChildrenisDisabled]: hasVariant(
                $state,
                "isDisabled",
                "isDisabled"
              ),

              [sty.slotTargetChildrenrounded]: hasVariant(
                $state,
                "rounded",
                "rounded"
              ),

              [sty.slotTargetChildrenshowEndIcon]: hasVariant(
                $state,
                "showEndIcon",
                "showEndIcon"
              ),

              [sty.slotTargetChildrensize_large]: hasVariant(
                $state,
                "size",
                "large"
              ),

              [sty.slotTargetChildrensize_large_rounded]:
                hasVariant($state, "size", "large") &&
                hasVariant($state, "rounded", "rounded"),
              [sty.slotTargetChildrensize_small]: hasVariant(
                $state,
                "size",
                "small"
              )
            })
          })
        : null}
      {(hasVariant($state, "showEndIcon", "showEndIcon") ? true : false) ? (
        <div
          className={classNames(projectcss.all, sty.freeBox__drHzf, {
            [sty.freeBoxshowEndIcon__drHzFhUlNp]: hasVariant(
              $state,
              "showEndIcon",
              "showEndIcon"
            ),

            [sty.freeBoxsize_small__drHzfL58]: hasVariant(
              $state,
              "size",
              "small"
            )
          })}
        >
          {(hasVariant($state, "showEndIcon", "showEndIcon") ? true : false)
            ? p.renderPlasmicSlot({
                defaultContents: (
                  <MenuIcon
                    className={classNames(projectcss.all, sty.svg__jB7A8)}
                    role={"img"}
                  />
                ),

                value: args.endIcon,
                className: classNames(sty.slotTargetEndIcon, {
                  [sty.slotTargetEndIconcolors_black]: hasVariant(
                    $state,
                    "colors",
                    "black"
                  ),

                  [sty.slotTargetEndIconcolors_link]: hasVariant(
                    $state,
                    "colors",
                    "link"
                  ),

                  [sty.slotTargetEndIconshowEndIcon]: hasVariant(
                    $state,
                    "showEndIcon",
                    "showEndIcon"
                  )
                })
              })
            : null}
        </div>
      ) : null}
    </p.Stack>
  );
}

function useBehavior(props, ref) {
  const b = pp.useButton(
    PlasmicButton,
    props,
    {
      showStartIconVariant: {
        group: "showStartIcon",
        variant: "showStartIcon"
      },
      showEndIconVariant: { group: "showEndIcon", variant: "showEndIcon" },
      isDisabledVariant: { group: "isDisabled", variant: "isDisabled" },
      contentSlot: "children",
      startIconSlot: "startIcon",
      endIconSlot: "endIcon",
      root: "root"
    },
    ref
  );

  return b;
}

const PlasmicDescendants = {
  mobiledeposit: ["mobiledeposit"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicButton__ArgProps,
          internalVariantPropNames: PlasmicButton__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "mobiledeposit") {
    func.displayName = "PlasmicButton";
  } else {
    func.displayName = `PlasmicButton.${nodeName}`;
  }
  return func;
}

export const PlasmicButton = Object.assign(
  // Top-level PlasmicButton renders the root element
  makeNodeComponent("mobiledeposit"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicButton
    internalVariantProps: PlasmicButton__VariantProps,
    internalArgProps: PlasmicButton__ArgProps,
    useBehavior
  }
);

export default PlasmicButton;
/* prettier-ignore-end */
