// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mzuCRszeeZdCMSdpkmycrs
// Component: vDntYEiI1rN5
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: sJnkaKbN1RIw/component
import Gamecontainers from "../../Gamecontainers"; // plasmic-import: FudiOxfuM-P6/component
import { useScreenVariants as useScreenVariantscWoeu4D18NgU } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: CWoeu4d18NgU/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_gv.module.css"; // plasmic-import: mzuCRszeeZdCMSdpkmycrs/projectcss
import sty from "./PlasmicLiveGames.module.css"; // plasmic-import: vDntYEiI1rN5/css
import HomeIcon from "./icons/PlasmicIcon__Home"; // plasmic-import: Kd2MFf3GbQ5_/icon
import liveTablespngVhz8JE5TGa7 from "./images/liveTablespng.png"; // plasmic-import: VHZ8J_e5tGA7/picture
import grandpng2WfRnZvWhXv5 from "./images/grandpng2.png"; // plasmic-import: wfRn-zvWHXv5/picture
import majorornamentpngBbFhQVirgbs from "./images/majorornamentpng.png"; // plasmic-import: _bbFhQVirgbs/picture
import minorpngVei898MEgnN from "./images/minorpng.png"; // plasmic-import: Vei898-mEgnN/picture
import minipng8ROhTd992RlW from "./images/minipng.png"; // plasmic-import: 8ROhTD992RlW/picture
import palmtreasuresTlszrL49Oo3 from "./images/palmtreasures.png"; // plasmic-import: TlszrL49oo_3/picture
import shoe15G4Jc91KueZqy from "./images/shoe15.png"; // plasmic-import: g4JC91KueZQY/picture

createPlasmicElementProxy;

export const PlasmicLiveGames__VariantProps = new Array();

export const PlasmicLiveGames__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicLiveGames__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantscWoeu4D18NgU()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"nav"}
            data-plasmic-override={overrides.nav}
            className={classNames("__wab_instance", sty.nav)}
          />

          <section
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"banner"}
              data-plasmic-override={overrides.banner}
              hasGap={true}
              className={classNames(projectcss.all, sty.banner)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___1KqZ)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "120px"
                      : "150px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: liveTablespngVhz8JE5TGa7,
                    fullWidth: 485,
                    fullHeight: 485,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            </p.Stack>
          </section>
          <section
            data-plasmic-name={"homenav"}
            data-plasmic-override={overrides.homenav}
            className={classNames(projectcss.all, sty.homenav)}
          >
            <HomeIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              onClick={async event => {
                const $steps = {};
              }}
              role={"img"}
            />
          </section>
          <section
            data-plasmic-name={"mainbody"}
            data-plasmic-override={overrides.mainbody}
            className={classNames(projectcss.all, sty.mainbody)}
          >
            {true ? (
              <div
                data-plasmic-name={"grandjackpot"}
                data-plasmic-override={overrides.grandjackpot}
                className={classNames(projectcss.all, sty.grandjackpot)}
              >
                <div
                  data-plasmic-name={"grand"}
                  data-plasmic-override={overrides.grand}
                  className={classNames(projectcss.all, sty.grand)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__o0Vaz)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "200px"
                        : "500px"
                    }
                    loading={"lazy"}
                    src={{
                      src: grandpng2WfRnZvWhXv5,
                      fullWidth: 595,
                      fullHeight: 196,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gbzR5
                    )}
                  >
                    {"GRAND JACKPOT"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__at9Fw
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"1234569 GVK"}
                      </span>
                    </React.Fragment>
                  </div>
                </div>
              </div>
            ) : null}
            {true ? (
              <div
                data-plasmic-name={"majorminormini"}
                data-plasmic-override={overrides.majorminormini}
                className={classNames(projectcss.all, sty.majorminormini)}
              >
                <div
                  data-plasmic-name={"major"}
                  data-plasmic-override={overrides.major}
                  className={classNames(projectcss.all, sty.major)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__d40Fb)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "106px"
                        : "auto"
                    }
                    loading={"lazy"}
                    src={{
                      src: majorornamentpngBbFhQVirgbs,
                      fullWidth: 372,
                      fullHeight: 160,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l5Gp1
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"MAJOR"}
                        </span>
                      </React.Fragment>
                    ) : (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"MAJOR JACKPOT"}
                        </span>
                      </React.Fragment>
                    )}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0JSo5
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"4565 GVK"}
                      </span>
                    </React.Fragment>
                  </div>
                </div>
                <div
                  data-plasmic-name={"minor"}
                  data-plasmic-override={overrides.minor}
                  className={classNames(projectcss.all, sty.minor)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ra1SU)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: minorpngVei898MEgnN,
                      fullWidth: 375,
                      fullHeight: 170,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___03HA5
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "MINOR"
                      : "MINOR JACKPOT"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8Jnq0
                    )}
                  >
                    {"789 GVK"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"mini"}
                  data-plasmic-override={overrides.mini}
                  className={classNames(projectcss.all, sty.mini)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__nqmXs)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: minipng8ROhTd992RlW,
                      fullWidth: 377,
                      fullHeight: 164,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__g9Gk4
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"MINI"}
                        </span>
                      </React.Fragment>
                    ) : (
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"MINI JACKPOT"}
                        </span>
                      </React.Fragment>
                    )}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mA8Q1
                    )}
                  >
                    {"51 GVK"}
                  </div>
                </div>
              </div>
            ) : null}
            <p.Stack
              as={"div"}
              data-plasmic-name={"palmsEgtIgt"}
              data-plasmic-override={overrides.palmsEgtIgt}
              hasGap={true}
              className={classNames(projectcss.all, sty.palmsEgtIgt)}
            >
              <Gamecontainers
                data-plasmic-name={"palms"}
                data-plasmic-override={overrides.palms}
                className={classNames("__wab_instance", sty.palms)}
                img={{
                  src: palmtreasuresTlszrL49Oo3,
                  fullWidth: 736,
                  fullHeight: 424,
                  aspectRatio: undefined
                }}
              />

              <Gamecontainers
                data-plasmic-name={"egt"}
                data-plasmic-override={overrides.egt}
                className={classNames("__wab_instance", sty.egt)}
                img={{
                  src: shoe15G4Jc91KueZqy,
                  fullWidth: 736,
                  fullHeight: 424,
                  aspectRatio: undefined
                }}
              />
            </p.Stack>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "nav",
    "header",
    "banner",
    "freeBox",
    "homenav",
    "svg",
    "mainbody",
    "grandjackpot",
    "grand",
    "majorminormini",
    "major",
    "minor",
    "mini",
    "palmsEgtIgt",
    "palms",
    "egt"
  ],

  nav: ["nav"],
  header: ["header", "banner", "freeBox"],
  banner: ["banner", "freeBox"],
  freeBox: ["freeBox"],
  homenav: ["homenav", "svg"],
  svg: ["svg"],
  mainbody: [
    "mainbody",
    "grandjackpot",
    "grand",
    "majorminormini",
    "major",
    "minor",
    "mini",
    "palmsEgtIgt",
    "palms",
    "egt"
  ],

  grandjackpot: ["grandjackpot", "grand"],
  grand: ["grand"],
  majorminormini: ["majorminormini", "major", "minor", "mini"],
  major: ["major"],
  minor: ["minor"],
  mini: ["mini"],
  palmsEgtIgt: ["palmsEgtIgt", "palms", "egt"],
  palms: ["palms"],
  egt: ["egt"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicLiveGames__ArgProps,
          internalVariantPropNames: PlasmicLiveGames__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicLiveGames__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLiveGames";
  } else {
    func.displayName = `PlasmicLiveGames.${nodeName}`;
  }
  return func;
}

export const PlasmicLiveGames = Object.assign(
  // Top-level PlasmicLiveGames renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    header: makeNodeComponent("header"),
    banner: makeNodeComponent("banner"),
    freeBox: makeNodeComponent("freeBox"),
    homenav: makeNodeComponent("homenav"),
    svg: makeNodeComponent("svg"),
    mainbody: makeNodeComponent("mainbody"),
    grandjackpot: makeNodeComponent("grandjackpot"),
    grand: makeNodeComponent("grand"),
    majorminormini: makeNodeComponent("majorminormini"),
    major: makeNodeComponent("major"),
    minor: makeNodeComponent("minor"),
    mini: makeNodeComponent("mini"),
    palmsEgtIgt: makeNodeComponent("palmsEgtIgt"),
    palms: makeNodeComponent("palms"),
    egt: makeNodeComponent("egt"),
    // Metadata about props expected for PlasmicLiveGames
    internalVariantProps: PlasmicLiveGames__VariantProps,
    internalArgProps: PlasmicLiveGames__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Live Games",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicLiveGames;
/* prettier-ignore-end */
